const FETCH_PRODUCT_SUCCESS='FETCH_PRODUCT_SUCCESS';
const FETCH_PRODUCT_FAILURE='FETCH_PRODUCT_FAILURE';
const FETCH_PRODUCT_REQUEST='FETCH_PRODUCT_REQUEST';

const SELECTED_PRODUCT_SUCCESS='SELECTED_PRODUCT_SUCCESS';
const SELECTED_PRODUCT_FAILURE='SELECTED_PRODUCT_FAILURE';
const SELECTED_PRODUCT_REQUEST='SELECTED_PRODUCT_REQUEST';

const REMOVE_SELECTED_PRODUCT='REMOVE_SELECTED_PRODUCT';

export  {FETCH_PRODUCT_FAILURE,
        FETCH_PRODUCT_REQUEST,
        FETCH_PRODUCT_SUCCESS,
        
        SELECTED_PRODUCT_SUCCESS,
        SELECTED_PRODUCT_FAILURE,
        SELECTED_PRODUCT_REQUEST,
        
        REMOVE_SELECTED_PRODUCT};
